### PR TITLE
rpm搜索导入subPath字段

### PR DESCRIPTION
**Pull request by leefanlllll**

### CODE REVIEW

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by ZWJason** [comment]
approve

**Review by ZWJason — APPROVED** [review]
approve

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareInput/22/22_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareInput/22/22_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareInput/22/22_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>dt覆盖率</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareInput/22/22_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareInput/22/22_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/704fc4f23f8a43efaa7a470bbb0b99ec/ddbc916a626c4ef2ba589c041f9d273c">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Review by 2511689622 — APPROVED** [review]
3 step skip

**Review by zhongjun2 — APPROVED** [review]

**Review by zhongjun2 — APPROVED** [review]

**Pull request closed without merging**
